config_01 = {'batch_size': 100,
             'hidden_size': 100,
             'num_layers': 3,
             'rnn_num_layers': 2,
             'init_mean': 0,
             'init_std': 0.1,
             'init_lr': 0.01,
             'anneal_period': 100,
             'anneal_ratio': 0.5,
             'num_epochs': 200,
             'linear_start': False,
             'max_grad_norm': 40,
             'keep_prob': 1.0}

config_02 = {'batch_size': 100,
             'hidden_size': 100,
             'num_layers': 3,
             'rnn_num_layers': 2,
             'init_mean': 0,
             'init_std': 0.1,
             'init_lr': 0.01,
             'anneal_period': 20,
             'anneal_ratio': 0.5,
             'num_epochs': 50,
             'linear_start': False,
             'max_grad_norm': 40,
             'keep_prob': 0.5,
             'mode': 'lc'}

config_03 = {'batch_size': 30,
             'hidden_size': 100,
             'num_layers': 3,
             'rnn_num_layers': 2,
             'init_mean': 0,
             'init_std': 0.1,
             'init_lr': 0.01,
             'anneal_period': 25,
             'anneal_ratio': 0.5,
             'num_epochs': 50,
             'linear_start': False,
             'max_grad_norm': 40,
             'keep_prob': 0.5,
             'mode': 'lca'}

config_04 = {'batch_size': 30,
             'hidden_size': 100,
             'num_layers': 3,
             'rnn_num_layers': 2,
             'init_mean': 0,
             'init_std': 0.1,
             'init_lr': 0.01,
             'anneal_period': 20,
             'anneal_ratio': 0.5,
             'num_epochs': 50,
             'linear_start': False,
             'max_grad_norm': 40,
             'keep_prob': 0.5,
             'mode': 'lca',
             'fold_path': 'data/s3/fold1.json'}

config_05 = {'batch_size': 30,
             'hidden_size': 100,
             'num_layers': 3,
             'rnn_num_layers': 2,
             'init_mean': 0,
             'init_std': 0.1,
             'init_lr': 0.01,
             'anneal_period': 25,
             'anneal_ratio': 0.5,
             'num_epochs': 50,
             'linear_start': False,
             'max_grad_norm': 40,
             'keep_prob': 1.0,
             'mode': 'lca'}

config_06 = {'batch_size': 25,
             'hidden_size': 100,
             'num_layers': 3,
             'rnn_num_layers': 2,
             'init_mean': 0,
             'init_std': 0.1,
             'init_lr': 0.01,
             'anneal_period': 25,
             'anneal_ratio': 0.5,
             'num_epochs': 50,
             'linear_start': False,
             'max_grad_norm': 40,
             'keep_prob': 0.9,
             'mode': 'lca'}

configs = {1: config_01, 2: config_02, 3: config_03, 4: config_04, 5: config_05, 6: config_06}
